name: README Testing

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Check README Content
      run: |
        # Check if the README contains the word "GitHub Actions"
        if grep -q "GitHub Actions" README.md; then
          echo "README test passed!"
          exit 0
        else
          echo "README test failed! The word 'GitHub Actions' is missing."
          exit 1
        fi
